import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/game_status.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'extended_game_dto.g.dart';

@JsonSerializable()
class ExtendedGameDto {
  ExtendedGameDto(
    this.id,
    this.startTime,
    this.gameNumber,
    this.teamA,
    this.teamB,
    this.pitch,
    this.leagueName,
    this.ageGroupName,
    this.pointsTeamA,
    this.pointsTeamB,
    this.status,
  );

  String id; // UUID as String
  DateTime startTime;
  int gameNumber;
  String teamA;
  String teamB;
  String pitch;
  String leagueName;
  String ageGroupName;
  int pointsTeamA;
  int pointsTeamB;
  @JsonKey(fromJson: _statusFromJson, toJson: _statusToJson)
  GameStatus status;

  static GameStatus _statusFromJson(String value) {
    return GameStatus.fromString(value);
  }

  static String _statusToJson(GameStatus status) {
    return status.value;
  }

  factory ExtendedGameDto.fromJson(Map<String, dynamic> json) =>
      _$ExtendedGameDtoFromJson(json);

  Map<String, dynamic> toJson() => _$ExtendedGameDtoToJson(this);
}
