import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'game_score_update_dto.g.dart';

@JsonSerializable()
class GameScoreUpdateDto {
  GameScoreUpdateDto(
    this.gameNumber,
    this.teamAScore,
    this.teamBScore,
  );

  int gameNumber;
  int teamAScore;
  int teamBScore;

  factory GameScoreUpdateDto.fromJson(Map<String, dynamic> json) =>
      _$GameScoreUpdateDtoFromJson(json);

  Map<String, dynamic> toJson() => _$GameScoreUpdateDtoToJson(this);
}
