import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'break_request_dto.g.dart';

@JsonSerializable()
class BreakRequestDto {
  BreakRequestDto(
    this.startTime,
    this.endTime,
    this.ageGroupName,
    this.message,
  );

  DateTime startTime;
  DateTime endTime;
  String ageGroupName; // UUID as String
  String message;

  factory BreakRequestDto.fromJson(Map<String, dynamic> json) =>
      _$BreakRequestDtoFromJson(json);

  Map<String, dynamic> toJson() => _$BreakRequestDtoToJson(this);
}
