import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/referee/game_dto.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'game_group_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class GameGroupDto {
  GameGroupDto(
    this.startTime,
    this.playTimeInSeconds,
  );

  DateTime startTime;
  /// Game duration in seconds (backend: playTimeInSeconds from GameScheduleDateTimeDTO).
  int playTimeInSeconds;
  List<GameDto> games = [];

  factory GameGroupDto.fromJson(Map<String, dynamic> json) =>
      _$GameGroupDtoFromJson(json);

  Map<String, dynamic> toJson() => _$GameGroupDtoToJson(this);
}
