import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'game_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class GameDto {
  GameDto(
    this.id,
    this.startTime,
    this.gameNumber,
    this.teamA,
    this.teamB,
    this.pitch,
    this.leagueName,
    this.ageGroupName,
    this.status,
    this.type,
  );

  String id; // UUID as String
  DateTime startTime;
  int gameNumber;
  String teamA; // Changed from TeamDto to String for GameScheduleDateTimeDTO
  String teamB; // Changed from TeamDto to String for GameScheduleDateTimeDTO
  String pitch; // Changed from PitchDto to String for GameScheduleDateTimeDTO
  String leagueName;
  String ageGroupName;
  String status;
  String type; // "GAME" or "BREAK"

  factory GameDto.fromJson(Map<String, dynamic> json) =>
      _$GameDtoFromJson(json);

  Map<String, dynamic> toJson() => _$GameDtoToJson(this);
}
