import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/game_status.dart';
import 'package:tournament_manager/src/serialization/schedule/item_type.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'game_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class GameDto {
  GameDto(
    this.id,
    this.startTime,
    this.gameNumber,
    this.teamA,
    this.teamB,
    this.pitch,
    this.leagueName,
    this.ageGroupName,
    this.status,
    this.type,
  );

  String id; // UUID as String
  DateTime startTime;
  int gameNumber;
  String teamA; // Changed from TeamDto to String for GameScheduleDateTimeDTO
  String teamB; // Changed from TeamDto to String for GameScheduleDateTimeDTO
  String pitch; // Changed from PitchDto to String for GameScheduleDateTimeDTO
  String leagueName;
  String ageGroupName;
  @JsonKey(fromJson: _statusFromJson, toJson: _statusToJson)
  GameStatus status;
  @JsonKey(fromJson: _typeFromJson, toJson: _typeToJson)
  ItemType type;

  static GameStatus _statusFromJson(String value) {
    return GameStatus.fromString(value);
  }

  static String _statusToJson(GameStatus status) {
    return status.value;
  }

  static ItemType _typeFromJson(String value) {
    return ItemType.fromString(value);
  }

  static String _typeToJson(ItemType type) {
    return type.value;
  }

  factory GameDto.fromJson(Map<String, dynamic> json) =>
      _$GameDtoFromJson(json);

  Map<String, dynamic> toJson() => _$GameDtoToJson(this);
}
