import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/age_group_dto.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'pitch_dto.g.dart';

@JsonSerializable()
class PitchDto {
  PitchDto(
    this.id,
    this.name,
    this.ageGroup,
  );

  String id; // UUID as String
  String name;
  AgeGroupDto? ageGroup; // Optional, may be null

  factory PitchDto.fromJson(Map<String, dynamic> json) =>
      _$PitchDtoFromJson(json);

  Map<String, dynamic> toJson() => _$PitchDtoToJson(this);
}
