import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'round_settings_dto.g.dart';

/// Entspricht EndQualificationRoundDetailedDTO (Backend).
/// POST /turnier/end-qualification-detailed
@JsonSerializable()
class RoundSettingsDto {
  RoundSettingsDto(
    this.maxTeamsPerLeaguePerAgeGroup,
    this.playTimeInSeconds,
    this.breakTimeInSeconds,
    this.roundName,
  );

  /// Altersgruppen-ID (UUID-String) -> max. Teams pro Liga
  final Map<String, int> maxTeamsPerLeaguePerAgeGroup;
  final int playTimeInSeconds;
  final int breakTimeInSeconds;
  final String roundName;

  factory RoundSettingsDto.fromJson(Map<String, dynamic> json) =>
      _$RoundSettingsDtoFromJson(json);

  Map<String, dynamic> toJson() => _$RoundSettingsDtoToJson(this);
}
