import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'timing_request_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class TimingRequestDto {
  TimingRequestDto(this.plannedStartTime);

  /// Planned start time of the slot (backend: plannedStartTime).
  DateTime plannedStartTime;

  factory TimingRequestDto.fromJson(Map<String, dynamic> json) =>
      _$TimingRequestDtoFromJson(json);

  Map<String, dynamic> toJson() => _$TimingRequestDtoToJson(this);
}
