import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/schedule/item_type.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'match_schedule_entry_dto.g.dart';

@JsonSerializable()
class MatchScheduleEntryDto {
  MatchScheduleEntryDto(
    this.itemType,
    this.pitchName,
    this.startTime,
    this.endTime,
    this.teamAName,
    this.teamBName,
    this.gameNumber,
  );

  @JsonKey(fromJson: _itemTypeFromJson, toJson: _itemTypeToJson)
  ItemType itemType;
  String pitchName;
  @JsonKey(fromJson: _dateTimeFromJson, toJson: _dateTimeToJson)
  DateTime startTime;
  @JsonKey(fromJson: _dateTimeFromJson, toJson: _dateTimeToJson)
  DateTime endTime;
  String? teamAName; // Optional, only for GAME
  String? teamBName; // Optional, only for GAME
  int? gameNumber; // Optional, only for GAME

  static DateTime _dateTimeFromJson(dynamic value) {
    if (value is String) {
      return DateTime.parse(value);
    }
    throw ArgumentError('Invalid DateTime format');
  }

  static String _dateTimeToJson(DateTime dateTime) {
    return dateTime.toIso8601String();
  }

  static ItemType _itemTypeFromJson(String value) {
    return ItemType.fromString(value);
  }

  static String _itemTypeToJson(ItemType itemType) {
    return itemType.value;
  }

  factory MatchScheduleEntryDto.fromJson(Map<String, dynamic> json) =>
      _$MatchScheduleEntryDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MatchScheduleEntryDtoToJson(this);
}
